version: '2'

services:
  nb-proxy:
    image: josdirksen/demo-haproxy
    container_name: nb-haproxy
    ports:
      - 1080:1080
      - 1081:1081
    environment:
      - CONSUL_ADDRESS=${DOCKER_CONSUL_IP}:8500
      - "constraint:node==nb1"

networks:
  default:
    external:
      name: my-net